### ISSUE TITLE
Can rules be learned from data?

### ISSUE THREAD

**Issue by ivannson** [Haghrah/PyIT2FLS#2]
More of a question than an issue, but I was wondering if the rules could be learned from data for a type 2 MIMO system?

**Comment by ivannson** [comment]
More of a question than an issue, but I was wondering if the rules could be learned from data for a type 2 MIMO system?

**Comment by Haghrah** [comment]
Of course, but explaining how it can be done, without an example, would be hard. So I will prepare an example in a few days and inform you.

**Comment by ivannson** [comment]
This is very kind of you, thank you!

**Comment by Haghrah** [comment]
Learning rules from data has two aspects, adjusting the sets and adjusting the rules. If adjusting the rules is done without adjusting the sets, then the results would not be satisfying. But, at the same time, adjusting the sets must be done in such a way that linguistic labels of them stay unchanged. So it is important to apply some constraints to the parameters of the sets while adjusting them. I'm not going to describe how the sets are adjusted, because there is an example about it, but I have prepared another example for describing how the rules can be adjusted. This example provides the basic concepts, and you should use a combinatorial optimization algorithm to complete it. The example code is [here](https://github.com/Haghrah/PyIT2FLS/blob/master/examples/ex_11.py)!

Assume that we have a two-input two-output MIMO system. Also, we have three sets corresponding with each input and output. So we can have nine rules in the rule base of our system. Let's define lists of the sets for each input and output as below:

```
X1Sets = [X1Small, X1Medium, X1Large]
X2Sets = [X2Small, X2Medium, X2Large]
Y1Sets = [Y1Small, Y1Medium, Y1Large]
Y2Sets = [Y2Small, Y2Medium, Y2Large]
```
And number of the sets for each input and output as:
```
nX1 = 3
nX2 = 3
nY1 = 3
nY2 = 3
```
Now we can represent every rule defined for this system as a list of 4 integers. For example, to represent the rule below as a list of integers:
```
IF x1 is X1Medium AND x2 is X2Large THEN y1 is Y1Small AND y2 is Y2Medium
```
we can write:
```
rule = [1, 2, 0, 1]
```
As can be seen, the first integer in the list is the index of X1Medium in the list X1Sets, and the second integer in the list is the index of X2Large in the list X2Sets. Similarly, the third and fourth integers are indices of the Y1Small and Y2Medium in the lists Y1Sets and Y2Sets. To continue, we need a function for generating nine random rules for creating the rule base:
```
def generateRuleBase():
    Rules = []
    for i in range(9):
        rule = [i // nX1, i % nX2, 
                random.randint(nY1), random.randint(nY2)]
        Rules.append(rule)
    return Rules
```
The next thing we need is an error function, which minimizing it, is equal to learning some data. For example, the error function can be something like this:
```
def error(R, D):
    # R: Rules
    # D: Data
    err = 0.
    myIT2FLS.rules = []
    for rule in R:
        myIT2FLS.add_rule([("x1", X1Sets[rule[0]]), ("x2", X2Sets[rule[1]])], 
                          [("y1", Y1Sets[rule[2]]), ("y2", Y2Sets[rule[3]])])
    for i in range(D.shape[1]):
        tr = myIT2FLS.evaluate({"x1":D[0, i], "x2":D[1, i]})
        err += (crisp(tr["y1"]) - D[2, i]) ** 2 + (crisp(tr["y2"]) - D[3, i]) ** 2
    return err
```
In the defined error function, the previous rule base of the system is cleared. Then the generated random rules are added to the rule base of the system. After completing the rule base, the input data are evaluated. In this example, it is assumed that the data is a 4xn np array. The first two rows indicate two inputs and the other two rows are the outputs. The main task for learning the rules is to generate a rule base that minimizes the error function. This can be achieved by using an optimization algorithm, for example, discrete GA. In my code, 100 random rule bases are generated, and the best one is shown at the end. I have also defined a rule base for the data manually. In some runs, there are randomly generated rule bases that are better than that. As it is said before, this code must be completed with two other parts. 
1) The sets must be also adjusted.
2) The rule bases must be improved using a population-based combinatorial optimization algorithm.

**Comment by ivannson** [comment]
Great explanation, thanks! Really appreciate the example too :)
